name: RomM-Comm
services:
  RomM-Comm:
    image: idiosync000/romm-comm:latest
    container_name: RomM-Comm
    environment:
      - TOKEN=${TOKEN} #Bot token
      - GUILD=${GUILD} #Guild token
      - API_URL=${API_URL}
      - USER=${USER} #RomM User
      - PASS=${PASS} #RomM Password
      - DOMAIN=${DOMAIN} #RomM Domain
      - SYNC_RATE=${SYNC_RATE}
      - REQUESTS_ENABLED=${REQUESTS_ENABLED}
      - IGDB_CLIENT_ID=${IGDB_CLIENT_ID}
      - IGDB_CLIENT_SECRET=${IGDB_CLIENT_SECRET}
      - ENABLE_USER_MANAGER=${ENABLE_USER_MANAGER}
      - AUTO_REGISTER_ROLE_ID=${AUTO_REGISTER_ROLE_ID}
      - UPDATE_VOICE_NAMES=${UPDATE_VOICE_NAMES}
      - CHANNEL_ID=${CHANNEL_ID}
      - SHOW_API_SUCCESS=${SHOW_API_SUCCESS}
      - CACHE_TTL=${CACHE_TTL}
      - API_TIMEOUT=${API_TIMEOUT}
    volumes:
      - ${DATADIR}:/app/data
    restart: unless-stopped